<?php
    session_start();
    if(isset($_SESSION['nombre_usuario'])){  
        header('location:view/users/dashboard.php');
        exit();
    }else{
        header('location:view/auth/login.php');
        exit();
    }
