-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.calle
(
    id_calle serial NOT NULL,
    nombre character varying(100) COLLATE pg_catalog."default" NOT NULL,
    sector character varying(100) COLLATE pg_catalog."default",
    descripcion text COLLATE pg_catalog."default",
    activo boolean DEFAULT true,
    fecha_registro timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    fecha_actualizacion timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT calle_pkey PRIMARY KEY (id_calle)
);

CREATE TABLE IF NOT EXISTS public.carga_familiar
(
    id_carga serial NOT NULL,
    id_habitante integer,
    id_jefe integer,
    parentesco character varying(50) COLLATE pg_catalog."default",
    activo boolean DEFAULT true,
    fecha_registro timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    fecha_actualizacion timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT carga_familiar_pkey PRIMARY KEY (id_carga)
);

CREATE TABLE IF NOT EXISTS public.comentario
(
    id_comentario serial NOT NULL,
    id_comunicado integer,
    id_usuario integer,
    contenido text COLLATE pg_catalog."default",
    fecha_comentario date,
    activo boolean DEFAULT true,
    fecha_registro timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    fecha_actualizacion timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT comentario_pkey PRIMARY KEY (id_comentario)
);

CREATE TABLE IF NOT EXISTS public.comunicado
(
    id_comunicado serial NOT NULL,
    id_usuario integer,
    titulo character varying(100) COLLATE pg_catalog."default",
    contenido text COLLATE pg_catalog."default",
    fecha_publicacion date,
    estado character varying(20) COLLATE pg_catalog."default",
    activo boolean DEFAULT true,
    fecha_registro timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    fecha_actualizacion timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT comunicado_pkey PRIMARY KEY (id_comunicado)
);

CREATE TABLE IF NOT EXISTS public.concepto_pago
(
    id_concepto serial NOT NULL,
    nombre character varying(100) COLLATE pg_catalog."default" NOT NULL,
    descripcion text COLLATE pg_catalog."default",
    activo boolean DEFAULT true,
    fecha_registro timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    fecha_actualizacion timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT concepto_pago_pkey PRIMARY KEY (id_concepto)
);

CREATE TABLE IF NOT EXISTS public.evento
(
    id_evento serial NOT NULL,
    titulo character varying(100) COLLATE pg_catalog."default",
    descripcion text COLLATE pg_catalog."default",
    fecha_evento date,
    lugar character varying(100) COLLATE pg_catalog."default",
    creado_por integer,
    activo boolean DEFAULT true,
    fecha_registro timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    fecha_actualizacion timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT evento_pkey PRIMARY KEY (id_evento)
);

CREATE TABLE IF NOT EXISTS public.habitante
(
    id_habitante serial NOT NULL,
    id_persona integer,
    fecha_ingreso date,
    condicion character varying(50) COLLATE pg_catalog."default",
    activo boolean DEFAULT true,
    fecha_registro timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    fecha_actualizacion timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT habitante_pkey PRIMARY KEY (id_habitante)
);

CREATE TABLE IF NOT EXISTS public.habitante_vivienda
(
    id_habitante integer NOT NULL,
    id_vivienda integer NOT NULL,
    es_jefe_familia boolean,
    fecha_inicio date,
    fecha_salida date,
    CONSTRAINT habitante_vivienda_pkey PRIMARY KEY (id_habitante, id_vivienda)
);

CREATE TABLE IF NOT EXISTS public.indicador_gestion
(
    id_indicador serial NOT NULL,
    nombre character varying(100) COLLATE pg_catalog."default",
    descripcion text COLLATE pg_catalog."default",
    valor numeric(10, 2),
    fecha_registro date,
    generado_por integer,
    activo boolean DEFAULT true,
    fecha_creacion timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    fecha_actualizacion timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT indicador_gestion_pkey PRIMARY KEY (id_indicador)
);

CREATE TABLE IF NOT EXISTS public.lider_calle
(
    id_habitante integer NOT NULL,
    id_calle integer NOT NULL,
    fecha_designacion date,
    activo boolean DEFAULT true,
    fecha_registro timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    fecha_actualizacion timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT lider_calle_pkey PRIMARY KEY (id_habitante, id_calle)
);

CREATE TABLE IF NOT EXISTS public.lider_comunal
(
    id_habitante integer NOT NULL,
    fecha_inicio date NOT NULL,
    fecha_fin date,
    observaciones text COLLATE pg_catalog."default",
    activo boolean DEFAULT true,
    fecha_registro timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    fecha_actualizacion timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT lider_comunal_pkey PRIMARY KEY (id_habitante)
);

CREATE TABLE IF NOT EXISTS public.pago
(
    id_pago serial NOT NULL,
    id_usuario integer,
    id_concepto integer,
    monto numeric(10, 2),
    fecha_pago date,
    estado_pago character varying(20) COLLATE pg_catalog."default",
    activo boolean DEFAULT true,
    fecha_registro timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    fecha_actualizacion timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pago_pkey PRIMARY KEY (id_pago)
);

CREATE TABLE IF NOT EXISTS public.participacion_evento
(
    id_participacion serial NOT NULL,
    id_evento integer,
    id_usuario integer,
    activo boolean DEFAULT true,
    fecha_registro timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    fecha_actualizacion timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT participacion_evento_pkey PRIMARY KEY (id_participacion)
);

CREATE TABLE IF NOT EXISTS public.persona
(
    id_persona serial NOT NULL,
    cedula character varying(19) COLLATE pg_catalog."default",
    nombres character varying(100) COLLATE pg_catalog."default" NOT NULL,
    apellidos character varying(100) COLLATE pg_catalog."default" NOT NULL,
    fecha_nacimiento date,
    sexo character varying(10) COLLATE pg_catalog."default",
    telefono character varying(20) COLLATE pg_catalog."default",
    direccion text COLLATE pg_catalog."default",
    correo character varying(100) COLLATE pg_catalog."default",
    estado character varying(20) COLLATE pg_catalog."default",
    activo boolean DEFAULT true,
    fecha_registro timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    fecha_actualizacion timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT persona_pkey PRIMARY KEY (id_persona),
    CONSTRAINT persona_cedula_key UNIQUE (cedula)
);

CREATE TABLE IF NOT EXISTS public.rol
(
    id_rol serial NOT NULL,
    nombre character varying(50) COLLATE pg_catalog."default" NOT NULL,
    descripcion text COLLATE pg_catalog."default",
    activo boolean DEFAULT true,
    fecha_registro timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    fecha_actualizacion timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT rol_pkey PRIMARY KEY (id_rol),
    CONSTRAINT rol_nombre_key UNIQUE (nombre)
);

CREATE TABLE IF NOT EXISTS public.usuario
(
    id_usuario serial NOT NULL,
    id_persona integer,
    id_rol integer,
    contrasena character varying(255) COLLATE pg_catalog."default" NOT NULL,
    fecha_registro timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    estado character varying(20) COLLATE pg_catalog."default",
    activo boolean DEFAULT true,
    fecha_actualizacion timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT usuario_pkey PRIMARY KEY (id_usuario)
);

CREATE TABLE IF NOT EXISTS public.vivienda
(
    id_vivienda serial NOT NULL,
    id_calle integer,
    direccion character varying(255) COLLATE pg_catalog."default",
    numero character varying(20) COLLATE pg_catalog."default",
    tipo character varying(50) COLLATE pg_catalog."default",
    estado character varying(20) COLLATE pg_catalog."default",
    activo boolean DEFAULT true,
    fecha_registro timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    fecha_actualizacion timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT vivienda_pkey PRIMARY KEY (id_vivienda)
);

ALTER TABLE IF EXISTS public.carga_familiar
    ADD CONSTRAINT carga_familiar_id_habitante_fkey FOREIGN KEY (id_habitante)
    REFERENCES public.habitante (id_habitante) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.carga_familiar
    ADD CONSTRAINT carga_familiar_id_jefe_fkey FOREIGN KEY (id_jefe)
    REFERENCES public.habitante (id_habitante) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.comentario
    ADD CONSTRAINT comentario_id_comunicado_fkey FOREIGN KEY (id_comunicado)
    REFERENCES public.comunicado (id_comunicado) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.comentario
    ADD CONSTRAINT comentario_id_usuario_fkey FOREIGN KEY (id_usuario)
    REFERENCES public.usuario (id_usuario) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.comunicado
    ADD CONSTRAINT comunicado_id_usuario_fkey FOREIGN KEY (id_usuario)
    REFERENCES public.usuario (id_usuario) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.evento
    ADD CONSTRAINT evento_creado_por_fkey FOREIGN KEY (creado_por)
    REFERENCES public.usuario (id_usuario) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.habitante
    ADD CONSTRAINT habitante_id_persona_fkey FOREIGN KEY (id_persona)
    REFERENCES public.persona (id_persona) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.habitante_vivienda
    ADD CONSTRAINT habitante_vivienda_id_habitante_fkey FOREIGN KEY (id_habitante)
    REFERENCES public.habitante (id_habitante) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.habitante_vivienda
    ADD CONSTRAINT habitante_vivienda_id_vivienda_fkey FOREIGN KEY (id_vivienda)
    REFERENCES public.vivienda (id_vivienda) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.indicador_gestion
    ADD CONSTRAINT indicador_gestion_generado_por_fkey FOREIGN KEY (generado_por)
    REFERENCES public.usuario (id_usuario) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.lider_calle
    ADD CONSTRAINT lider_calle_id_calle_fkey FOREIGN KEY (id_calle)
    REFERENCES public.calle (id_calle) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.lider_calle
    ADD CONSTRAINT lider_calle_id_habitante_fkey FOREIGN KEY (id_habitante)
    REFERENCES public.habitante (id_habitante) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.lider_comunal
    ADD CONSTRAINT lider_comunal_id_habitante_fkey FOREIGN KEY (id_habitante)
    REFERENCES public.habitante (id_habitante) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS lider_comunal_pkey
    ON public.lider_comunal(id_habitante);


ALTER TABLE IF EXISTS public.pago
    ADD CONSTRAINT pago_id_concepto_fkey FOREIGN KEY (id_concepto)
    REFERENCES public.concepto_pago (id_concepto) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.pago
    ADD CONSTRAINT pago_id_usuario_fkey FOREIGN KEY (id_usuario)
    REFERENCES public.usuario (id_usuario) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.participacion_evento
    ADD CONSTRAINT participacion_evento_id_evento_fkey FOREIGN KEY (id_evento)
    REFERENCES public.evento (id_evento) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.participacion_evento
    ADD CONSTRAINT participacion_evento_id_usuario_fkey FOREIGN KEY (id_usuario)
    REFERENCES public.usuario (id_usuario) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.usuario
    ADD CONSTRAINT usuario_id_persona_fkey FOREIGN KEY (id_persona)
    REFERENCES public.persona (id_persona) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.usuario
    ADD CONSTRAINT usuario_id_rol_fkey FOREIGN KEY (id_rol)
    REFERENCES public.rol (id_rol) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.vivienda
    ADD CONSTRAINT vivienda_id_calle_fkey FOREIGN KEY (id_calle)
    REFERENCES public.calle (id_calle) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

END;